# Generated by Django 4.2.2 on 2023-06-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_permisos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormularioUsuariosDB',
        ),
    ]
